name: Gitiki wiki

debug: false
locale: en

extensions:
    Gitiki\CodeHighlight\CodeHighlightExtension:
        style: tomorrow
    Gitiki\Redirector\RedirectorExtension: ~
    Gitiki\Git\GitExtension:
        git_dir: ../
        wiki_dir: wiki/
